image: docker:24.0.7

stages:
  - build
  - deploy

default:
  before_script:
    - touch .env
    - /bin/sh ./bin/ci-cd/before-script.sh

variables:
  REGISTRY: artifacts.mitre.org:8200

# Build the docker images and push to the Docker repo
Build:
  stage: build
  tags:
    - build
  variables:
    # Specify User and Group ID to prevent permissions issues on shared volumes
    GROUP_ID: 901
    USER_ID: 900
  script:
    - docker compose build --build-arg GROUP_ID=$GROUP_ID --build-arg USER_ID=$USER_ID
    - docker compose push

Deploy to conflict-ob:
  before_script:
    - cp $dotenv_conflict_ob ./.env
    - /bin/sh ./bin/ci-cd/before-script.sh
  stage: deploy
  tags:
    - deploy_co
  variables:
    DEPLOY_ENV: conflict_ob
  script:
    # Source the env vars in .env
    - set -a; . ./.env; set +a
    - SETTINGS_TIMESTAMP=$(date +%s) docker stack deploy -c docker-compose.yml --with-registry-auth caesar-co
  only:
    - main