version: '3'

services:
  bayanat:
    volumes:
      - ${ENV_FILE:-.env}:/app/.env
      - $PWD:/app/
    depends_on:
      redis:
        condition: service_healthy
  
  celery:
    volumes:
      - ${ENV_FILE:-.env}:/app/.env
      - $PWD:/app/
    depends_on:
      redis:
        condition: service_healthy

  postgres:
    profiles:
      - local