version: '3'

services:
  postgres:
    image: 'postgis/postgis:15-3.3'
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    ports:
      - ${POSTGRES_EXTERNAL_PORT:-5432}:5432
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /var/run/postgresql
    healthcheck:
      test: "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
      interval: 3s
      retries: 10

  redis:
    image: 'redis:latest'
    ports:
      - ${REDIS_EXTERNAL_PORT:-6379}:6379
    command: redis-server --requirepass '${REDIS_PASSWORD}'
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - redis_data:/var/lib/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 3s
      retries: 10

  bayanat:
    image: bayanat
    build:
      context: .
      dockerfile: ./flask/Dockerfile
      args:
        - ROLE=flask
        - ENV_FILE=${ENV_FILE:-.env}
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-change-me}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
    volumes:
      - '${MEDIA_PATH:-./enferno/media}:/app/enferno/media:rw'
      - './enferno/imports:/app/enferno/imports:rw'
      - './logs:/app/logs:rw'
      - ${ENV_FILE:-.env}:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    ports:
      - ${BAYANAT_EXTERNAL_PORT:-5000}:5000

  celery:
    image: celery
    build:
      context: .
      dockerfile: ./flask/Dockerfile
      args:
        - ROLE=celery
        - ENV_FILE=${ENV_FILE:-.env}
    volumes_from:
      - bayanat
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    restart: always
    image: 'bitnami/nginx:latest'
    ports:
      - '80:80'
    profiles:
      - nginx
    volumes:
      - './enferno/static/:/app/static/:ro'
      - './nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro'
      - './nginx/bayanat.conf:/opt/bitnami/nginx/conf/server_blocks/bayanat.conf:ro'
    depends_on:
      - bayanat
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /opt/bitnami/nginx/tmp/
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 3s
      retries: 10

volumes:
  redis_data:
  postgres_data:
