version: '3'

services:
  bayanat:
    volumes:
      - ${ENV_FILE:-.env}:/app/.env
      - $PWD:/app/
  
  celery:
    volumes:
      - ${ENV_FILE:-.env}:/app/.env
      - $PWD:/app/
  
  nginx:
    restart: always
    image: 'bitnami/nginx:latest'
    ports:
      - ${NGINX_EXTERNAL_PORT:-80}:80
    profiles:
      - nginx
    volumes:
      - ${NGINX_STATIC_PATH:-./enferno/static/}:/app/static/:ro
      - ${NGINX_CONF_PATH:-./nginx/nginx.conf}:/opt/bitnami/nginx/conf/nginx.conf:ro
      - ${NGINX_BAYANAT_CONF_PATH:-./nginx/bayanat.conf}:/opt/bitnami/nginx/conf/server_blocks/bayanat.conf:ro
    depends_on:
      - bayanat
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /opt/bitnami/nginx/tmp/
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 3s
      retries: 10