version: '3'

services:
  bayanat:
    volumes:
      - ${ENV_FILE:-.env}:/app/.env
      - $PWD:/app/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  celery:
    volumes:
      - ${ENV_FILE:-.env}:/app/.env
      - $PWD:/app/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  nginx:
    restart: always
    image: 'bitnami/nginx:latest'
    ports:
      - ${NGINX_EXTERNAL_PORT:-80}:80
    profiles:
      - nginx
    volumes:
      - ${NGINX_STATIC_PATH:-./enferno/static/}:/app/static/:ro
      - ${NGINX_CONF_PATH:-./nginx/nginx.conf}:/opt/bitnami/nginx/conf/nginx.conf:ro
      - ${NGINX_BAYANAT_CONF_PATH:-./nginx/bayanat.conf}:/opt/bitnami/nginx/conf/server_blocks/bayanat.conf:ro
    depends_on:
      - bayanat
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /opt/bitnami/nginx/tmp/
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - ${PWD}/.devcontainer/pgadmin-servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: caesar@localhost.net
      PGADMIN_DEFAULT_PASSWORD: change-me
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    depends_on:
      - postgres
