version: "3"

services:
  bayanat:
    volumes:
      - ${ENV_FILE:-.env}:/app/.env
      - $PWD:/app/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    volumes:
      - ${ENV_FILE:-.env}:/app/.env
      - $PWD:/app/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_EXTERNAL_PORT:-5050}:80"
    profiles:
      - pgadmin
    volumes:
      - ${PWD}/.devcontainer/pgadmin-servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: caesar@localhost.net
      PGADMIN_DEFAULT_PASSWORD: change-me
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    depends_on:
      - postgres

  postgres:
    volumes:
      - ${DB_DATA:-./pgdata}:/var/lib/postgresql/data
