"""upgrade tables to add a created_by field

Revision ID: 2a87f2bcf52a
Revises: 5ed276f106be
Create Date: 2024-07-09 21:12:42.412801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from migrations.utils import column_exists

# revision identifiers, used by Alembic.
revision = '2a87f2bcf52a'
down_revision = '5ed276f106be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        if not column_exists('actor', 'created_by_id', op):
            batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('bulletin', schema=None) as batch_op:
        if not column_exists('bulletin', 'created_by_id', op):
            batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('incident', schema=None) as batch_op:
        if not column_exists('incident', 'created_by_id', op):
            batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        if column_exists('incident', 'created_by_id', op):
            batch_op.drop_column('created_by_id')

    with op.batch_alter_table('bulletin', schema=None) as batch_op:
        if column_exists('bulletin', 'created_by_id', op):
            batch_op.drop_column('created_by_id')

    with op.batch_alter_table('actor', schema=None) as batch_op:
        if column_exists('actor', 'created_by_id', op):
            batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
