"""change location type from point to geometry

Revision ID: 2ee3f48f476a
Revises: d010e7127040
Create Date: 2024-06-20 20:23:30.652601

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2 
from sqlalchemy.dialects import postgresql
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '2ee3f48f476a'
down_revision = 'd010e7127040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('latlng',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('latlng',
               existing_type=geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)

    # ### end Alembic commands ###
