"""adding geolocations to events

Revision ID: 3584b4f321bb
Revises: 4239158c5584
Create Date: 2024-08-27 19:31:48.517242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from migrations.utils import column_exists

# revision identifiers, used by Alembic.
revision = '3584b4f321bb'
down_revision = '4239158c5584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        if not column_exists('event', 'geo_location_id', op):
            batch_op.add_column(sa.Column('geo_location_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'geo_location', ['geo_location_id'], ['id'])

    with op.batch_alter_table('geo_location', schema=None) as batch_op:
        if not column_exists('geo_location', 'event_id', op):
            batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        if column_exists('geo_location', 'bulletin_id', op):
            batch_op.drop_constraint('geo_location_bulletin_id_fkey', type_='foreignkey')
            batch_op.drop_column('bulletin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geo_location', schema=None) as batch_op:
        if not column_exists('geo_location', 'bulletin_id', op):
            batch_op.add_column(sa.Column('bulletin_id', sa.INTEGER(), autoincrement=False, nullable=True))
            batch_op.create_foreign_key('geo_location_bulletin_id_fkey', 'bulletin', ['bulletin_id'], ['id'])
        if column_exists('geo_location', 'event_id', op):
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.drop_column('event_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        if column_exists('event', 'geo_location_id', op):
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.drop_column('geo_location_id')
    # ### end Alembic commands ###
