"""add organization type

Revision ID: 4239158c5584
Revises: 3f5a4c7479f9
Create Date: 2024-09-11 14:54:25.711359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from migrations.utils import column_exists

# revision identifiers, used by Alembic.
revision = '4239158c5584'
down_revision = '3f5a4c7479f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        if not column_exists('organization', 'organization_type_id', op):
            batch_op.add_column(sa.Column('organization_type_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'organization_type', ['organization_type_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        if column_exists('organization', 'organization_type_id', op):
            batch_op.drop_constraint('organization_organization_type_id_fkey', type_='foreignkey')
            batch_op.drop_column('organization_type_id')
    # ### end Alembic commands ###
