"""add shapefile group uuid to media

Revision ID: 6bd1eb5fcb42
Revises: 4694b7b87906
Create Date: 2024-10-31 19:41:14.821603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from migrations.utils import column_exists

# revision identifiers, used by Alembic.
revision = '6bd1eb5fcb42'
down_revision = '4694b7b87906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        if not column_exists('media', 'shapefile_group_uuid', op):
            batch_op.add_column(sa.Column('shapefile_group_uuid', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('media', schema=None) as batch_op:
        if column_exists('media', 'shapefile_group_uuid', op):
            batch_op.drop_column('shapefile_group_uuid')

    # ### end Alembic commands ###
