"""add sub type field to actor

Revision ID: 6dd1ac87ad7e
Revises: c3ad319cd39b
Create Date: 2024-06-20 19:39:33.687369

"""
from alembic import op
from migrations.utils import column_exists
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dd1ac87ad7e'
down_revision = 'c3ad319cd39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        if not column_exists('actor', 'sub_type_id', op):
            batch_op.add_column(sa.Column('sub_type_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_actor_sub_type_id_actor_sub_type', 'actor_sub_type', ['sub_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        if column_exists('actor', 'sub_type_id', op):
            batch_op.drop_constraint('fk_actor_sub_type_id_actor_sub_type', type_='foreignkey')
            batch_op.drop_column('sub_type_id')

    # ### end Alembic commands ###
