"""Adding custom_location to events

Revision ID: 7fda62cc1156
Revises: 3584b4f321bb
Create Date: 2024-09-04 02:49:59.006251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from migrations.utils import column_exists

# revision identifiers, used by Alembic.
revision = '7fda62cc1156'
down_revision = '3584b4f321bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        if not column_exists('event', 'custom_location', op):
            batch_op.add_column(sa.Column('custom_location', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        if column_exists('event', 'custom_location', op):
            batch_op.drop_column('custom_location')
    # ### end Alembic commands ###
