"""change latlng to geometry

Revision ID: f87bf63ebb11
Revises: 5ed276f106be
Create Date: 2024-07-11 23:55:43.710437

"""
from alembic import op
from migrations.utils import column_exists

# revision identifiers, used by Alembic.
revision = 'f87bf63ebb11'
down_revision = '5ed276f106be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geo_location', schema=None) as batch_op:
        batch_op.alter_column('latlng', new_column_name='geometry')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('latlng', new_column_name='geometry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('geometry', new_column_name='latlng')

    with op.batch_alter_table('geo_location', schema=None) as batch_op:
        batch_op.alter_column('geometry', new_column_name='latlng')
    # ### end Alembic commands ###
