"""change latlng to geometry

Revision ID: f87bf63ebb11
Revises: 5ed276f106be
Create Date: 2024-07-11 23:55:43.710437

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2 
from sqlalchemy.dialects import postgresql
from geoalchemy2 import Geometry
from migrations.utils import column_exists

# revision identifiers, used by Alembic.
revision = 'f87bf63ebb11'
down_revision = '5ed276f106be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('geo_location', schema=None) as batch_op:
        if not column_exists('geo_location', 'geometry', op):
            batch_op.add_column(sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
        if column_exists('geo_location', 'latlng', op):
            batch_op.drop_index('idx_geo_location_latlng', postgresql_using='gist', if_exists=True)
            batch_op.drop_column('latlng')

    with op.batch_alter_table('location', schema=None) as batch_op:
        if not column_exists('location', 'geometry', op):
            batch_op.add_column(sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
        if column_exists('location', 'latlng', op):
            batch_op.drop_index('idx_location_latlng', postgresql_using='gist', if_exists=True)
            batch_op.drop_column('latlng')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('location', schema=None) as batch_op:
        if not column_exists('location', 'latlng', op):
            batch_op.add_column(sa.Column('latlng', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
        if column_exists('location', 'geometry', op):
            batch_op.drop_index('idx_location_geometry', postgresql_using='gist', if_exists=True)
            batch_op.drop_column('geometry')

    with op.batch_alter_table('geo_location', schema=None) as batch_op:
        if not column_exists('geo_location', 'latlng', op):
            batch_op.add_column(sa.Column('latlng', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
        if column_exists('geo_location', 'geometry', op):
            batch_op.drop_index('idx_geo_location_geometry', postgresql_using='gist', if_exists=True)
            batch_op.drop_column('geometry')

    # ### end Alembic commands ###
